version: '3'
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public
    environment:
      - NODE_ENV=production